'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        return queryInterface.bulkInsert('Patients', [
            {
                userId: 58,
                dob: '1995-01-01',
                gender: '0',
                ethnicity: 'Kinh',
                address: '123 Nguyễn Trãi, Hà Nội',
                insuranceTerm: '2024-01-01 to 2025-01-01',
                insuranceNumber: 'INS123',
                familyAddress: 'Same as above',
                notePMH: 'No allergies',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 59,
                dob: '1988-02-02',
                gender: '1',
                ethnicity: 'Kinh',
                address: '456 Lê Lợi, TP. Hồ Chí Minh',
                insuranceTerm: '2024-02-01 to 2025-02-01',
                insuranceNumber: 'INS456',
                familyAddress: 'Same as above',
                notePMH: 'Hypertension',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 60,
                dob: '2000-03-03',
                gender: '0',
                ethnicity: 'Kinh',
                address: '789 Trần Phú, Đà Nẵng',
                insuranceTerm: '2024-03-01 to 2025-03-01',
                insuranceNumber: 'INS789',
                familyAddress: 'Same as above',
                notePMH: 'Diabetes',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 61,
                dob: '1992-04-04',
                gender: '1',
                ethnicity: 'Kinh',
                address: '101 Phạm Ngọc Thạch, Cần Thơ',
                insuranceTerm: '2024-04-01 to 2025-04-01',
                insuranceNumber: 'INS101',
                familyAddress: 'Same as above',
                notePMH: 'Asthma',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 62,
                dob: '1985-05-05',
                gender: '0',
                ethnicity: 'Kinh',
                address: '112 Võ Văn Tần, Hải Phòng',
                insuranceTerm: '2024-05-01 to 2025-05-01',
                insuranceNumber: 'INS112',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 63,
                dob: '1998-06-06',
                gender: '1',
                ethnicity: 'Kinh',
                address: '134 Nguyễn Thị Minh Khai, Huế',
                insuranceTerm: '2024-06-01 to 2025-06-01',
                insuranceNumber: 'INS134',
                familyAddress: 'Same as above',
                notePMH: 'Allergy to penicillin',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 64,
                dob: '1979-07-07',
                gender: '0',
                ethnicity: 'Kinh',
                address: '156 Pasteur, Nha Trang',
                insuranceTerm: '2024-07-01 to 2025-07-01',
                insuranceNumber: 'INS156',
                familyAddress: 'Same as above',
                notePMH: 'High cholesterol',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 65,
                dob: '2002-08-08',
                gender: '1',
                ethnicity: 'Kinh',
                address: '178 Điện Biên Phủ, Vũng Tàu',
                insuranceTerm: '2024-08-01 to 2025-08-01',
                insuranceNumber: 'INS178',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 66,
                dob: '1991-09-09',
                gender: '0',
                ethnicity: 'Kinh',
                address: '200 Hai Bà Trưng, Biên Hòa',
                insuranceTerm: '2024-09-01 to 2025-09-01',
                insuranceNumber: 'INS200',
                familyAddress: 'Same as above',
                notePMH: 'Thyroid issues',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 67,
                dob: '1984-10-10',
                gender: '1',
                ethnicity: 'Kinh',
                address: '222 Lý Tự Trọng, Buôn Ma Thuột',
                insuranceTerm: '2024-10-01 to 2025-10-01',
                insuranceNumber: 'INS222',
                familyAddress: 'Same as above',
                notePMH: 'Anemia',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 68,
                dob: '1997-11-11',
                gender: '0',
                ethnicity: 'Kinh',
                address: '244 Bà Triệu, Hà Nội',
                insuranceTerm: '2024-11-01 to 2025-11-01',
                insuranceNumber: 'INS244',
                familyAddress: 'Same as above',
                notePMH: 'No allergies',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 69,
                dob: '1986-12-12',
                gender: '1',
                ethnicity: 'Kinh',
                address: '266 Hàng Bông, TP. Hồ Chí Minh',
                insuranceTerm: '2024-12-01 to 2025-12-01',
                insuranceNumber: 'INS266',
                familyAddress: 'Same as above',
                notePMH: 'Migraines',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 70,
                dob: '2001-01-13',
                gender: '0',
                ethnicity: 'Kinh',
                address: '288 Trần Hưng Đạo, Đà Nẵng',
                insuranceTerm: '2025-01-01 to 2026-01-01',
                insuranceNumber: 'INS288',
                familyAddress: 'Same as above',
                notePMH: 'Eczema',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 71,
                dob: '1993-02-14',
                gender: '1',
                ethnicity: 'Kinh',
                address: '310 Hàng Đào, Cần Thơ',
                insuranceTerm: '2025-02-01 to 2026-02-01',
                insuranceNumber: 'INS310',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 72,
                dob: '1982-03-15',
                gender: '0',
                ethnicity: 'Kinh',
                address: '332 Nguyễn Công Trứ, Hải Phòng',
                insuranceTerm: '2025-03-01 to 2026-03-01',
                insuranceNumber: 'INS332',
                familyAddress: 'Same as above',
                notePMH: 'Arthritis',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 73,
                dob: '1996-04-16',
                gender: '1',
                ethnicity: 'Kinh',
                address: '354 Võ Văn Tần, Huế',
                insuranceTerm: '2025-04-01 to 2026-04-01',
                insuranceNumber: 'INS354',
                familyAddress: 'Same as above',
                notePMH: 'Allergy to shellfish',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 74,
                dob: '1987-05-17',
                gender: '0',
                ethnicity: 'Kinh',
                address: '376 Nam Kỳ Khởi Nghĩa, Nha Trang',
                insuranceTerm: '2025-05-01 to 2026-05-01',
                insuranceNumber: 'INS376',
                familyAddress: 'Same as above',
                notePMH: 'GERD',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 75,
                dob: '2003-06-18',
                gender: '1',
                ethnicity: 'Kinh',
                address: '398 Lê Thánh Tôn, Vũng Tàu',
                insuranceTerm: '2025-06-01 to 2026-06-01',
                insuranceNumber: 'INS398',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 76,
                dob: '1994-07-19',
                gender: '0',
                ethnicity: 'Kinh',
                address: '420 Hàng Bạc, Biên Hòa',
                insuranceTerm: '2025-07-01 to 2026-07-01',
                insuranceNumber: 'INS420',
                familyAddress: 'Same as above',
                notePMH: 'Insomnia',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 77,
                dob: '1983-08-20',
                gender: '1',
                ethnicity: 'Kinh',
                address: '442 Hàng Mã, Buôn Ma Thuột',
                insuranceTerm: '2025-08-01 to 2026-08-01',
                insuranceNumber: 'INS442',
                familyAddress: 'Same as above',
                notePMH: 'Depression',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 78,
                dob: '1999-09-21',
                gender: '0',
                ethnicity: 'Kinh',
                address: '464 Bà Triệu, Hà Nội',
                insuranceTerm: '2025-09-01 to 2026-09-01',
                insuranceNumber: 'INS464',
                familyAddress: 'Same as above',
                notePMH: 'No allergies',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 79,
                dob: '1989-10-22',
                gender: '1',
                ethnicity: 'Kinh',
                address: '486 Hàng Bông, TP. Hồ Chí Minh',
                insuranceTerm: '2025-10-01 to 2026-10-01',
                insuranceNumber: 'INS486',
                familyAddress: 'Same as above',
                notePMH: 'Anxiety',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 80,
                dob: '2004-11-23',
                gender: '0',
                ethnicity: 'Kinh',
                address: '508 Trần Hưng Đạo, Đà Nẵng',
                insuranceTerm: '2025-11-01 to 2026-11-01',
                insuranceNumber: 'INS508',
                familyAddress: 'Same as above',
                notePMH: 'ADHD',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 81,
                dob: '1990-12-24',
                gender: '1',
                ethnicity: 'Kinh',
                address: '530 Hàng Đào, Cần Thơ',
                insuranceTerm: '2025-12-01 to 2026-12-01',
                insuranceNumber: 'INS530',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 82,
                dob: '1981-01-25',
                gender: '0',
                ethnicity: 'Kinh',
                address: '552 Nguyễn Công Trứ, Hải Phòng',
                insuranceTerm: '2026-01-01 to 2027-01-01',
                insuranceNumber: 'INS552',
                familyAddress: 'Same as above',
                notePMH: 'Osteoporosis',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 83,
                dob: '1995-02-26',
                gender: '1',
                ethnicity: 'Kinh',
                address: '574 Võ Văn Tần, Huế',
                insuranceTerm: '2026-02-01 to 2027-02-01',
                insuranceNumber: 'INS574',
                familyAddress: 'Same as above',
                notePMH: 'PCOS',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 84,
                dob: '1984-03-27',
                gender: '0',
                ethnicity: 'Kinh',
                address: '596 Nam Kỳ Khởi Nghĩa, Nha Trang',
                insuranceTerm: '2026-03-01 to 2027-03-01',
                insuranceNumber: 'INS596',
                familyAddress: 'Same as above',
                notePMH: 'Prostate issues',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 85,
                dob: '2000-04-28',
                gender: '1',
                ethnicity: 'Kinh',
                address: '618 Lê Thánh Tôn, Vũng Tàu',
                insuranceTerm: '2026-04-01 to 2027-04-01',
                insuranceNumber: 'INS618',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 86,
                dob: '1992-05-29',
                gender: '0',
                ethnicity: 'Kinh',
                address: '640 Hàng Bạc, Biên Hòa',
                insuranceTerm: '2026-05-01 to 2027-05-01',
                insuranceNumber: 'INS640',
                familyAddress: 'Same as above',
                notePMH: 'COPD',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 87,
                dob: '1985-06-30',
                gender: '1',
                ethnicity: 'Kinh',
                address: '662 Hàng Mã, Buôn Ma Thuột',
                insuranceTerm: '2026-06-01 to 2027-06-01',
                insuranceNumber: 'INS662',
                familyAddress: 'Same as above',
                notePMH: 'Scoliosis',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 88,
                dob: '1998-07-01',
                gender: '0',
                ethnicity: 'Kinh',
                address: '684 Bà Triệu, Hà Nội',
                insuranceTerm: '2026-07-01 to 2027-07-01',
                insuranceNumber: 'INS684',
                familyAddress: 'Same as above',
                notePMH: 'Celiac disease',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 89,
                dob: '1987-08-02',
                gender: '1',
                ethnicity: 'Kinh',
                address: '706 Hàng Bông, TP. Hồ Chí Minh',
                insuranceTerm: '2026-08-01 to 2027-08-01',
                insuranceNumber: 'INS706',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 90,
                dob: '2003-09-03',
                gender: '0',
                ethnicity: 'Kinh',
                address: '728 Trần Hưng Đạo, Đà Nẵng',
                insuranceTerm: '2026-09-01 to 2027-09-01',
                insuranceNumber: 'INS728',
                familyAddress: 'Same as above',
                notePMH: 'Allergy to nuts',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 91,
                dob: '1993-10-04',
                gender: '1',
                ethnicity: 'Kinh',
                address: '750 Hàng Đào, Cần Thơ',
                insuranceTerm: '2026-10-01 to 2027-10-01',
                insuranceNumber: 'INS750',
                familyAddress: 'Same as above',
                notePMH: 'Hypertension',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 92,
                dob: '1986-11-05',
                gender: '0',
                ethnicity: 'Kinh',
                address: '772 Nguyễn Công Trứ, Hải Phòng',
                insuranceTerm: '2026-11-01 to 2027-11-01',
                insuranceNumber: 'INS772',
                familyAddress: 'Same as above',
                notePMH: 'Diabetes',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 93,
                dob: '1999-12-06',
                gender: '1',
                ethnicity: 'Kinh',
                address: '794 Võ Văn Tần, Huế',
                insuranceTerm: '2026-12-01 to 2027-12-01',
                insuranceNumber: 'INS794',
                familyAddress: 'Same as above',
                notePMH: 'Asthma',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 94,
                dob: '1988-01-07',
                gender: '0',
                ethnicity: 'Kinh',
                address: '816 Nam Kỳ Khởi Nghĩa, Nha Trang',
                insuranceTerm: '2027-01-01 to 2028-01-01',
                insuranceNumber: 'INS816',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 95,
                dob: '2001-02-08',
                gender: '1',
                ethnicity: 'Kinh',
                address: '838 Lê Thánh Tôn, Vũng Tàu',
                insuranceTerm: '2027-02-01 to 2028-02-01',
                insuranceNumber: 'INS838',
                familyAddress: 'Same as above',
                notePMH: 'Allergy to pollen',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 96,
                dob: '1994-03-09',
                gender: '0',
                ethnicity: 'Kinh',
                address: '860 Hàng Bạc, Biên Hòa',
                insuranceTerm: '2027-03-01 to 2028-03-01',
                insuranceNumber: 'INS860',
                familyAddress: 'Same as above',
                notePMH: 'High cholesterol',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 97,
                dob: '1983-04-10',
                gender: '1',
                ethnicity: 'Kinh',
                address: '882 Hàng Mã, Buôn Ma Thuột',
                insuranceTerm: '2027-04-01 to 2028-04-01',
                insuranceNumber: 'INS882',
                familyAddress: 'Same as above',
                notePMH: 'Thyroid issues',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 98,
                dob: '1997-05-11',
                gender: '0',
                ethnicity: 'Kinh',
                address: '904 Bà Triệu, Hà Nội',
                insuranceTerm: '2027-05-01 to 2028-05-01',
                insuranceNumber: 'INS904',
                familyAddress: 'Same as above',
                notePMH: 'Anemia',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 99,
                dob: '1989-06-12',
                gender: '1',
                ethnicity: 'Kinh',
                address: '926 Hàng Bông, TP. Hồ Chí Minh',
                insuranceTerm: '2027-06-01 to 2028-06-01',
                insuranceNumber: 'INS926',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 100,
                dob: '2002-07-13',
                gender: '0',
                ethnicity: 'Kinh',
                address: '948 Trần Hưng Đạo, Đà Nẵng',
                insuranceTerm: '2027-07-01 to 2028-07-01',
                insuranceNumber: 'INS948',
                familyAddress: 'Same as above',
                notePMH: 'Migraines',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 101,
                dob: '1991-08-14',
                gender: '1',
                ethnicity: 'Kinh',
                address: '970 Hàng Đào, Cần Thơ',
                insuranceTerm: '2027-08-01 to 2028-08-01',
                insuranceNumber: 'INS970',
                familyAddress: 'Same as above',
                notePMH: 'Eczema',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 102,
                dob: '1984-09-15',
                gender: '0',
                ethnicity: 'Kinh',
                address: '992 Nguyễn Công Trứ, Hải Phòng',
                insuranceTerm: '2027-09-01 to 2028-09-01',
                insuranceNumber: 'INS992',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 103,
                dob: '1996-10-16',
                gender: '1',
                ethnicity: 'Kinh',
                address: '1014 Võ Văn Tần, Huế',
                insuranceTerm: '2027-10-01 to 2028-10-01',
                insuranceNumber: 'INS1014',
                familyAddress: 'Same as above',
                notePMH: 'Arthritis',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 104,
                dob: '1985-11-17',
                gender: '0',
                ethnicity: 'Kinh',
                address: '1036 Nam Kỳ Khởi Nghĩa, Nha Trang',
                insuranceTerm: '2027-11-01 to 2028-11-01',
                insuranceNumber: 'INS1036',
                familyAddress: 'Same as above',
                notePMH: 'Allergy to shellfish',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 105,
                dob: '2000-12-18',
                gender: '1',
                ethnicity: 'Kinh',
                address: '1058 Lê Thánh Tôn, Vũng Tàu',
                insuranceTerm: '2027-12-01 to 2028-12-01',
                insuranceNumber: 'INS1058',
                familyAddress: 'Same as above',
                notePMH: 'GERD',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 106,
                dob: '1992-01-19',
                gender: '0',
                ethnicity: 'Kinh',
                address: '1080 Hàng Bạc, Biên Hòa',
                insuranceTerm: '2028-01-01 to 2029-01-01',
                insuranceNumber: 'INS1080',
                familyAddress: 'Same as above',
                notePMH: 'No history',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 107,
                dob: '1983-02-20',
                gender: '1',
                ethnicity: 'Kinh',
                address: '1102 Hàng Mã, Buôn Ma Thuột',
                insuranceTerm: '2028-02-01 to 2029-02-01',
                insuranceNumber: 'INS1102',
                familyAddress: 'Same as above',
                notePMH: 'Insomnia',
                createdAt: new Date(),
                updatedAt: new Date()
            }
        ]);
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    }
};
