'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        return queryInterface.bulkInsert('Doctors', [
            {
                userId: 3,
                specialtyId: 1,
                dob: '1985-05-15',
                gender: '0',
                ethnicity: 'Kinh',
                address: '45 Lê Lợi, TP. Hồ Chí Minh',
                degree: 'Thạc sĩ - Tim mạch',
                room: '201',
                image: '/uploads/users/doc1.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 4,
                specialtyId: 2,
                dob: '1978-11-22',
                gender: '1',
                ethnicity: 'Kinh',
                address: '67 Nguyễn Huệ, Đà Nẵng',
                degree: 'Tiến sĩ - Nhi khoa',
                room: '202',
                image: '/uploads/users/doc2.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 5,
                specialtyId: 3,
                dob: '1990-03-10',
                gender: '0',
                ethnicity: 'Kinh',
                address: '89 Trần Phú, Hà Nội',
                degree: 'Bác sĩ chuyên khoa I - Da liễu',
                room: '203',
                image: '/uploads/users/doc3.webp',
                price: 400000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 6,
                specialtyId: 4,
                dob: '1982-07-18',
                gender: '0',
                ethnicity: 'Kinh',
                address: '12 Phạm Ngọc Thạch, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa II - Tai mũi họng',
                room: '204',
                image: '/uploads/users/doc4.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 7,
                specialtyId: 5,
                dob: '1988-09-25',
                gender: '0',
                ethnicity: 'Kinh',
                address: '34 Lê Duẩn, Đà Nẵng',
                degree: 'Thạc sĩ - Mắt',
                room: '205',
                image: '/uploads/users/doc5.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 8,
                specialtyId: 6,
                dob: '1975-04-12',
                gender: '1',
                ethnicity: 'Kinh',
                address: '56 Hai Bà Trưng, Hà Nội',
                degree: 'Tiến sĩ - Răng hàm mặt',
                room: '206',
                image: '/uploads/users/doc6.webp',
                price: 700000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 9,
                specialtyId: 7,
                dob: '1992-01-30',
                gender: '1',
                ethnicity: 'Kinh',
                address: '78 Nguyễn Thị Minh Khai, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa I - Phụ khoa',
                room: '207',
                image: '/uploads/users/doc7.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 10,
                specialtyId: 8,
                dob: '1980-06-05',
                gender: '1',
                ethnicity: 'Kinh',
                address: '90 Pasteur, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa II - Nam khoa',
                room: '208',
                image: '/uploads/users/doc8.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 11,
                specialtyId: 9,
                dob: '1987-08-14',
                gender: '0',
                ethnicity: 'Kinh',
                address: '23 Lý Tự Trọng, Hà Nội',
                degree: 'Thạc sĩ - Hô hấp',
                room: '209',
                image: '/uploads/users/doc9.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 12,
                specialtyId: 10,
                dob: '1979-02-20',
                gender: '0',
                ethnicity: 'Kinh',
                address: '45 Điện Biên Phủ, TP. Hồ Chí Minh',
                degree: 'Tiến sĩ - Nội tiết',
                room: '210',
                image: '/uploads/users/doc10.webp',
                price: 650000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 13,
                specialtyId: 11,
                dob: '1991-10-08',
                gender: '0',
                ethnicity: 'Kinh',
                address: '67 Bà Triệu, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa I - Ung thư',
                room: '211',
                image: '/uploads/users/doc11.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 14,
                specialtyId: 12,
                dob: '1983-12-17',
                gender: '0',
                ethnicity: 'Kinh',
                address: '89 Hàng Bông, Hà Nội',
                degree: 'Bác sĩ chuyên khoa II - Dinh dưỡng',
                room: '212',
                image: '/uploads/users/doc12.webp',
                price: 400000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 15,
                specialtyId: 13,
                dob: '1989-04-26',
                gender: '1',
                ethnicity: 'Kinh',
                address: '12 Võ Văn Tần, TP. Hồ Chí Minh',
                degree: 'Thạc sĩ - Tâm lý',
                room: '213',
                image: '/uploads/users/doc13.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 16,
                specialtyId: 14,
                dob: '1976-09-03',
                gender: '1',
                ethnicity: 'Kinh',
                address: '34 Trần Hưng Đạo, Đà Nẵng',
                degree: 'Tiến sĩ - Dị ứng',
                room: '214',
                image: '/uploads/users/doc14.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 17,
                specialtyId: 15,
                dob: '1993-11-11',
                gender: '0',
                ethnicity: 'Kinh',
                address: '56 Hàng Đào, Hà Nội',
                degree: 'Bác sĩ chuyên khoa I - Lão khoa',
                room: '215',
                image: '/uploads/users/doc15.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 18,
                specialtyId: 16,
                dob: '1981-05-28',
                gender: '0',
                ethnicity: 'Kinh',
                address: '78 Nguyễn Công Trứ, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa II - Sản khoa',
                room: '216',
                image: '/uploads/users/doc16.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 19,
                specialtyId: 17,
                dob: '1986-07-07',
                gender: '0',
                ethnicity: 'Kinh',
                address: '90 Hàng Mã, Đà Nẵng',
                degree: 'Thạc sĩ - Truyền nhiễm',
                room: '217',
                image: '/uploads/users/doc17.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 20,
                specialtyId: 18,
                dob: '1974-01-15',
                gender: '0',
                ethnicity: 'Kinh',
                address: '23 Hàng Bạc, Hà Nội',
                degree: 'Tiến sĩ - Thận tiết niệu',
                room: '218',
                image: '/uploads/users/doc18.webp',
                price: 650000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 21,
                specialtyId: 19,
                dob: '1990-03-24',
                gender: '0',
                ethnicity: 'Kinh',
                address: '45 Lê Thánh Tôn, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa I - Gan mật',
                room: '219',
                image: '/uploads/users/doc19.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 22,
                specialtyId: 20,
                dob: '1984-08-02',
                gender: '1',
                ethnicity: 'Kinh',
                address: '67 Hàng Trống, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa II - Huyết học',
                room: '220',
                image: '/uploads/users/doc20.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 23,
                specialtyId: 21,
                dob: '1992-10-19',
                gender: '1',
                ethnicity: 'Kinh',
                address: '89 Hàng Gai, Hà Nội',
                degree: 'Thạc sĩ - Phục hồi chức năng',
                room: '221',
                image: '/uploads/users/doc21.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 24,
                specialtyId: 22,
                dob: '1977-12-28',
                gender: '0',
                ethnicity: 'Kinh',
                address: '12 Đồng Khởi, TP. Hồ Chí Minh',
                degree: 'Tiến sĩ - Cơ xương khớp',
                room: '222',
                image: '/uploads/users/doc22.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 25,
                specialtyId: 23,
                dob: '1988-02-06',
                gender: '0',
                ethnicity: 'Kinh',
                address: '34 Hàng Bài, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa I - Thần kinh',
                room: '223',
                image: '/uploads/users/doc23.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 26,
                specialtyId: 24,
                dob: '1980-04-15',
                gender: '1',
                ethnicity: 'Kinh',
                address: '56 Hàng Điếu, Hà Nội',
                degree: 'Bác sĩ chuyên khoa II - Tiêu hóa',
                room: '224',
                image: '/uploads/users/doc24.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 27,
                specialtyId: 25,
                dob: '1991-06-23',
                gender: '0',
                ethnicity: 'Kinh',
                address: '78 Nam Kỳ Khởi Nghĩa, TP. Hồ Chí Minh',
                degree: 'Thạc sĩ - Tim mạch',
                room: '225',
                image: '/uploads/users/doc25.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 28,
                specialtyId: 22,
                dob: '1983-09-01',
                gender: '0',
                ethnicity: 'Kinh',
                address: '90 Hàng Bông, Đà Nẵng',
                degree: 'Tiến sĩ - Tai mũi họng',
                room: '226',
                image: '/uploads/users/doc26.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 29,
                specialtyId: 7,
                dob: '1989-11-09',
                gender: '0',
                ethnicity: 'Kinh',
                address: '23 Hàng Mã, Hà Nội',
                degree: 'Bác sĩ chuyên khoa I - Da liễu',
                room: '227',
                image: '/uploads/users/doc27.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 30,
                specialtyId: 8,
                dob: '1975-01-18',
                gender: '0',
                ethnicity: 'Kinh',
                address: '45 Lê Thánh Tôn, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa II - Nhi khoa',
                room: '228',
                image: '/uploads/users/doc28.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 31,
                specialtyId: 9,
                dob: '1993-03-27',
                gender: '1',
                ethnicity: 'Kinh',
                address: '67 Hàng Trống, Đà Nẵng',
                degree: 'Thạc sĩ - Phụ khoa',
                room: '229',
                image: '/uploads/users/doc29.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 32,
                specialtyId: 2,
                dob: '1981-05-05',
                gender: '1',
                ethnicity: 'Kinh',
                address: '89 Hàng Gai, Hà Nội',
                degree: 'Tiến sĩ - Nam khoa',
                room: '230',
                image: '/uploads/users/doc30.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 33,
                specialtyId: 1,
                dob: '1987-07-14',
                gender: '0',
                ethnicity: 'Kinh',
                address: '12 Đồng Khởi, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa I - Mắt',
                room: '231',
                image: '/uploads/users/doc31.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 34,
                specialtyId: 2,
                dob: '1979-09-22',
                gender: '1',
                ethnicity: 'Kinh',
                address: '34 Hàng Bài, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa II - Răng hàm mặt',
                room: '232',
                image: '/uploads/users/doc32.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 35,
                specialtyId: 3,
                dob: '1990-11-30',
                gender: '0',
                ethnicity: 'Kinh',
                address: '56 Hàng Điếu, Hà Nội',
                degree: 'Thạc sĩ - Hô hấp',
                room: '233',
                image: '/uploads/users/doc33.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 36,
                specialtyId: 4,
                dob: '1984-02-08',
                gender: '0',
                ethnicity: 'Kinh',
                address: '78 Nam Kỳ Khởi Nghĩa, TP. Hồ Chí Minh',
                degree: 'Tiến sĩ - Nội tiết',
                room: '234',
                image: '/uploads/users/doc34.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 37,
                specialtyId: 5,
                dob: '1992-04-17',
                gender: '0',
                ethnicity: 'Kinh',
                address: '90 Hàng Bông, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa I - Ung thư',
                room: '235',
                image: '/uploads/users/doc35.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 38,
                specialtyId: 6,
                dob: '1976-06-25',
                gender: '0',
                ethnicity: 'Kinh',
                address: '23 Hàng Mã, Hà Nội',
                degree: 'Bác sĩ chuyên khoa II - Dinh dưỡng',
                room: '236',
                image: '/uploads/users/doc36.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 39,
                specialtyId: 7,
                dob: '1988-08-03',
                gender: '0',
                ethnicity: 'Kinh',
                address: '45 Lê Thánh Tôn, TP. Hồ Chí Minh',
                degree: 'Thạc sĩ - Tâm lý',
                room: '237',
                image: '/uploads/users/doc37.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 40,
                specialtyId: 8,
                dob: '1980-10-12',
                gender: '0',
                ethnicity: 'Kinh',
                address: '67 Hàng Trống, Đà Nẵng',
                degree: 'Tiến sĩ - Dị ứng',
                room: '238',
                image: '/uploads/users/doc38.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 41,
                specialtyId: 9,
                dob: '1991-12-20',
                gender: '0',
                ethnicity: 'Kinh',
                address: '89 Hàng Gai, Hà Nội',
                degree: 'Bác sĩ chuyên khoa I - Lão khoa',
                room: '239',
                image: '/uploads/users/doc39.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 42,
                specialtyId: 10,
                dob: '1983-02-28',
                gender: '0',
                ethnicity: 'Kinh',
                address: '12 Đồng Khởi, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa II - Sản khoa',
                room: '240',
                image: '/uploads/users/doc40.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 43,
                specialtyId: 11,
                dob: '1989-05-07',
                gender: '1',
                ethnicity: 'Kinh',
                address: '34 Hàng Bài, Đà Nẵng',
                degree: 'Thạc sĩ - Truyền nhiễm',
                room: '241',
                image: '/uploads/users/doc41.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 44,
                specialtyId: 12,
                dob: '1977-07-16',
                gender: '0',
                ethnicity: 'Kinh',
                address: '56 Hàng Điếu, Hà Nội',
                degree: 'Tiến sĩ - Thận tiết niệu',
                room: '242',
                image: '/uploads/users/doc42.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 45,
                specialtyId: 13,
                dob: '1990-09-24',
                gender: '0',
                ethnicity: 'Kinh',
                address: '78 Nam Kỳ Khởi Nghĩa, TP. Hồ Chí Minh',
                degree: 'Bác sĩ chuyên khoa I - Gan mật',
                room: '243',
                image: '/uploads/users/doc43.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 46,
                specialtyId: 14,
                dob: '1982-11-02',
                gender: '0',
                ethnicity: 'Kinh',
                address: '90 Hàng Bông, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa II - Huyết học',
                room: '244',
                image: '/uploads/users/doc44.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 47,
                specialtyId: 15,
                dob: '1988-01-11',
                gender: '0',
                ethnicity: 'Kinh',
                address: '23 Hàng Mã, Hà Nội',
                degree: 'Thạc sĩ - Phục hồi chức năng',
                room: '245',
                image: '/uploads/users/doc45.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 48,
                specialtyId: 16,
                dob: '1980-03-19',
                gender: '1',
                ethnicity: 'Kinh',
                address: '45 Lê Thánh Tôn, TP. Hồ Chí Minh',
                degree: 'Tiến sĩ - Cơ xương khớp',
                room: '246',
                image: '/uploads/users/doc46.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 49,
                specialtyId: 17,
                dob: '1991-05-28',
                gender: '1',
                ethnicity: 'Kinh',
                address: '67 Hàng Trống, Đà Nẵng',
                degree: 'Bác sĩ chuyên khoa I - Thần kinh',
                room: '247',
                image: '/uploads/users/doc47.webp',
                price: 450000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 50,
                specialtyId: 18,
                dob: '1983-08-05',
                gender: '1',
                ethnicity: 'Kinh',
                address: '89 Hàng Gai, Hà Nội',
                degree: 'Bác sĩ chuyên khoa II - Tiêu hóa',
                room: '248',
                image: '/uploads/users/doc48.webp',
                price: 550000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 51,
                specialtyId: 19,
                dob: '1989-10-14',
                gender: '0',
                ethnicity: 'Kinh',
                address: '12 Đồng Khởi, TP. Hồ Chí Minh',
                degree: 'Thạc sĩ - Tim mạch',
                room: '249',
                image: '/uploads/users/doc49.webp',
                price: 500000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                userId: 52,
                specialtyId: 20,
                dob: '1977-12-22',
                gender: '0',
                ethnicity: 'Kinh',
                address: '34 Hàng Bài, Đà Nẵng',
                degree: 'Tiến sĩ - Tai mũi họng',
                room: '250',
                image: '/uploads/users/doc50.webp',
                price: 600000,
                status: 'active',
                createdAt: new Date(),
                updatedAt: new Date()
            }
        ]);
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    }
};
